# Generated by Django 6.1.1 on 2026-10-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_abrazapinos', '0003_post_author_post_visibility_profile_bike_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Oculta por moderación'),
        ),
    ]
