# Generated by Django 6.1.1 on 2026-10-07 10:10

from django.db import migrations, models


# Añade imagen opcional al post; el blank preserva la compatibilidad con publicaciones existentes.
class Migration(migrations.Migration):

    dependencies = [
        ('social_abrazapinos', '0004_post_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='publicaciones/'),
        ),
    ]
