# Generated by Django 6.1.1 on 2026-09-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_abrazapinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
