# Generated by Django 6.1.1 on 2026-10-01 09:39

from django.db import migrations, models


# Añade el vínculo con Checkout y limita los nuevos pedidos al flujo de Stripe.
class Migration(migrations.Migration):

    dependencies = [
        ('shop_abrazapinos', '0004_pedido_pais_pedido_provincia_alter_pedido_estado'),
    ]

    operations = [
        # La sesión puede quedar vacía en pedidos históricos creados antes de Stripe.
        migrations.AddField(
            model_name='pedido',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        # Incorpora estados de pago sin eliminar los estados previos de preparación.
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('preparando', 'En preparación'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        # Stripe reemplaza las opciones locales que no procesaban ningún cobro.
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Stripe')], max_length=24),
        ),
    ]
