# Generated by Django 6.1.1 on 2026-10-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_abrazapinos', '0005_pedido_stripe_session_id_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
    ]
