# Generated by Django 6.1.1 on 2026-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_abrazapinos', '0006_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='talla',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='requires_size',
            field=models.BooleanField(default=False, verbose_name='Requiere seleccionar talla'),
        ),
    ]
